/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoutesImport } from './routes/Routes'
import { Route as ProtectedRouteImport } from './routes/ProtectedRoute'
import { Route as RegisterPageIndexImport } from './routes/RegisterPage/index'
import { Route as MainPageIndexImport } from './routes/MainPage/index'
import { Route as LoginPageIndexImport } from './routes/LoginPage/index'

// Create/Update Routes

const RoutesRoute = RoutesImport.update({
  id: '/Routes',
  path: '/Routes',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRouteRoute = ProtectedRouteImport.update({
  id: '/ProtectedRoute',
  path: '/ProtectedRoute',
  getParentRoute: () => rootRoute,
} as any)

const RegisterPageIndexRoute = RegisterPageIndexImport.update({
  id: '/RegisterPage/',
  path: '/RegisterPage/',
  getParentRoute: () => rootRoute,
} as any)

const MainPageIndexRoute = MainPageIndexImport.update({
  id: '/MainPage/',
  path: '/MainPage/',
  getParentRoute: () => rootRoute,
} as any)

const LoginPageIndexRoute = LoginPageIndexImport.update({
  id: '/LoginPage/',
  path: '/LoginPage/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ProtectedRoute': {
      id: '/ProtectedRoute'
      path: '/ProtectedRoute'
      fullPath: '/ProtectedRoute'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/Routes': {
      id: '/Routes'
      path: '/Routes'
      fullPath: '/Routes'
      preLoaderRoute: typeof RoutesImport
      parentRoute: typeof rootRoute
    }
    '/LoginPage/': {
      id: '/LoginPage/'
      path: '/LoginPage'
      fullPath: '/LoginPage'
      preLoaderRoute: typeof LoginPageIndexImport
      parentRoute: typeof rootRoute
    }
    '/MainPage/': {
      id: '/MainPage/'
      path: '/MainPage'
      fullPath: '/MainPage'
      preLoaderRoute: typeof MainPageIndexImport
      parentRoute: typeof rootRoute
    }
    '/RegisterPage/': {
      id: '/RegisterPage/'
      path: '/RegisterPage'
      fullPath: '/RegisterPage'
      preLoaderRoute: typeof RegisterPageIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/ProtectedRoute': typeof ProtectedRouteRoute
  '/Routes': typeof RoutesRoute
  '/LoginPage': typeof LoginPageIndexRoute
  '/MainPage': typeof MainPageIndexRoute
  '/RegisterPage': typeof RegisterPageIndexRoute
}

export interface FileRoutesByTo {
  '/ProtectedRoute': typeof ProtectedRouteRoute
  '/Routes': typeof RoutesRoute
  '/LoginPage': typeof LoginPageIndexRoute
  '/MainPage': typeof MainPageIndexRoute
  '/RegisterPage': typeof RegisterPageIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/ProtectedRoute': typeof ProtectedRouteRoute
  '/Routes': typeof RoutesRoute
  '/LoginPage/': typeof LoginPageIndexRoute
  '/MainPage/': typeof MainPageIndexRoute
  '/RegisterPage/': typeof RegisterPageIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ProtectedRoute'
    | '/Routes'
    | '/LoginPage'
    | '/MainPage'
    | '/RegisterPage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ProtectedRoute'
    | '/Routes'
    | '/LoginPage'
    | '/MainPage'
    | '/RegisterPage'
  id:
    | '__root__'
    | '/ProtectedRoute'
    | '/Routes'
    | '/LoginPage/'
    | '/MainPage/'
    | '/RegisterPage/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRoute
  RoutesRoute: typeof RoutesRoute
  LoginPageIndexRoute: typeof LoginPageIndexRoute
  MainPageIndexRoute: typeof MainPageIndexRoute
  RegisterPageIndexRoute: typeof RegisterPageIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRoute,
  RoutesRoute: RoutesRoute,
  LoginPageIndexRoute: LoginPageIndexRoute,
  MainPageIndexRoute: MainPageIndexRoute,
  RegisterPageIndexRoute: RegisterPageIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/ProtectedRoute",
        "/Routes",
        "/LoginPage/",
        "/MainPage/",
        "/RegisterPage/"
      ]
    },
    "/ProtectedRoute": {
      "filePath": "ProtectedRoute.tsx"
    },
    "/Routes": {
      "filePath": "Routes.tsx"
    },
    "/LoginPage/": {
      "filePath": "LoginPage/index.tsx"
    },
    "/MainPage/": {
      "filePath": "MainPage/index.tsx"
    },
    "/RegisterPage/": {
      "filePath": "RegisterPage/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
